{
 "title": "FullNode",
 "description": "Lotus FullNode",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(lotus_daemon_version, instance)"
    }
   },
   {
    "name": "Version",
    "label": "version",
    "query": {
     "query": "label_values(lotus_daemon_version{instance=\"$instance\"}, version)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Chain Sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sync Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(lotus_daemon_chain_height{instance=\"$instance\"}) - (sum(lotus_daemon_sync_status{instance=\"$instance\"}) by (height) / count(lotus_daemon_sync_status{instance=\"$instance\"} != 0))"
    }
   ]
  },
  {
   "title": "Chain Height",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(lotus_daemon_sync_status{instance=\"$instance\"}) by (height)"
    }
   ]
  },
  {
   "title": "Chain Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "lotus_daemon_sync_status{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "BaseFee",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "attoFIL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(lotus_daemon_basefee{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "BaseFee Timeline",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "attoFIL" } },
   "yaxes": [
    { "format": "attoFIL" }
   ],
   "targets": [
    {
     "expr": "max(lotus_daemon_basefee{instance=\"$instance\"})"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(lotus_daemon_net_peers{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Total In",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "lotus_daemon_net_bandwidth{stats=\"TotalIn\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Out",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "lotus_daemon_net_bandwidth{stats=\"TotalOut\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 14 },
   "targets": [
    {
     "expr": "lotus_daemon_net_peers{instance=\"$instance\"}"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "lotus_daemon_net_bandwidth{stats=\"RateOut\",instance=\"$instance\"}",
     "legendFormat": "In"
    },
    {
     "expr": "lotus_daemon_net_bandwidth{stats=\"RateIn\",instance=\"$instance\"}",
     "legendFormat": "Out"
    }
   ]
  },
  { "title": "Wallet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Wallet Balance",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "lotus_daemon_wallet_balance{instance=\"$instance\"}"
    }
   ]
  },
  { "title": "Message Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Pending Message Pool",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 31 },
   "targets": [
    { "expr": "lotus_daemon_mpool_pending" }
   ]
  }
 ]
}