{
 "title": "Miner",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "miner_id",
    "label": "ID",
    "query": {
     "query": "label_values(lotus_miner_version, miner_id)"
    }
   },
   {
    "name": "Version",
    "label": "version",
    "query": {
     "query": "label_values(lotus_miner_version{miner_id=\"$miner_id\"}, version)"
    }
   },
   {
    "name": "sector_task",
    "label": "Sector Task",
    "query": {
     "query": "label_values(lotus_miner_sealing_job{miner_id=\"$miner_id\"}, sector_task)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Wallet Balance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Wallet Balance",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "FIL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lotus_miner_balance{miner_id=\"$miner_id\", state=\"Balance\"}",
     "legendFormat": "Miner ALL"
    },
    {
     "expr": "lotus_market_balance{miner_id=\"$miner_id\", state=\"Balance\"}",
     "legendFormat": "Market ALL"
    },
    {
     "expr": "sum(lotus_actor_control_list{miner_id=\"$miner_id\", use=~\"post|precommit|commit\"})",
     "legendFormat": "Control ALL"
    },
    {
     "expr": "lotus_actor_control_list{miner_id=\"$miner_id\", name=\"owner\"}",
     "legendFormat": "Worker"
    },
    {
     "expr": "sum(lotus_miner_balance{miner_id=\"$miner_id\", state=\"Available\"}) + sum(lotus_market_balance{miner_id=\"$miner_id\", state=\"Available\"}) + sum(lotus_actor_control_list{miner_id=\"$miner_id\", use=~\"post|precommit|commit\"}) + sum(lotus_actor_control_list{miner_id=\"$miner_id\", name=\"owner\"})",
     "legendFormat": "Total Spendable"
    }
   ]
  },
  {
   "title": "Miner Balance",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "lotus_miner_balance{state=~\"PreCommit|Pledge|Vesting|Available\", miner_id=\"$miner_id\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Market Balance",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "lotus_market_balance{state=~\"Locked|Available\", miner_id=\"$miner_id\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  { "title": "Power & Sectors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Power",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lotus_power{miner_id=\"$miner_id\", state=\"Total Raw Byte Power\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "lotus_power{miner_id=\"$miner_id\", state=\"Total Quality Adj Power\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "lotus_power{miner_id=\"$miner_id\", state=\"Miner Raw Byte Power\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "lotus_power{miner_id=\"$miner_id\", state=\"Miner Quality Adj Power\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "max(lotus_miner_sectors_states_count{miner_id=\"$miner_id\", state=\"Proving\"}) * max(lotus_miner_sector_size{miner_id=\"f08157\"})",
     "legendFormat": "Committed Power"
    }
   ]
  },
  {
   "title": "Expected block win rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "/ Day" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(lotus_power{miner_id=\"$miner_id\", state=\"Miner Quality Adj Power\"})/sum(lotus_power{miner_id=\"$miner_id\", state=\"Total Quality Adj Power\"})*5*60*2*24"
    }
   ]
  },
  {
   "title": "Power Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(lotus_power{state=\"Miner Raw Byte Power\",miner_id=\"$miner_id\"}) / max(lotus_power{state=\"Total Raw Byte Power\",miner_id=\"$miner_id\"}) * 100",
     "legendFormat": "Raw Byte Power Rate"
    },
    {
     "expr": "max(lotus_power{state=\"Miner Quality Adj Power\",miner_id=\"$miner_id\"}) / max(lotus_power{state=\"Total Quality Adj Power\",miner_id=\"$miner_id\"}) * 100",
     "legendFormat": "Quality Adj Power Rate"
    }
   ]
  },
  {
   "title": "Expected  block every time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1/(sum(lotus_power{miner_id=\"$miner_id\", state=\"Miner Quality Adj Power\"})/sum(lotus_power{miner_id=\"$miner_id\", state=\"Total Quality Adj Power\"})*2*5/60)"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Running Jobs",
   "type": "table",
   "description": "Update every 15 minutes",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "lotus_miner_sealing_job{miner_id=\"$miner_id\"}"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(lotus_miner_sealing_job{miner_id=\"$miner_id\"}) by (sector_task)",
     "legendFormat": "{{ sector_task }}"
    }
   ]
  },
  {
   "title": "seal/v0/precommit/1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(lotus_miner_sealing_job{miner_id=\"$miner_id\", sector_task=\"seal/v0/precommit/1\"}) by (sector_from_worker_hostname)",
     "legendFormat": "{{ sector_from_worker_hostname }}"
    }
   ]
  },
  {
   "title": "seal/v0/precommit/2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(lotus_miner_sealing_job{miner_id=\"$miner_id\", sector_task=\"seal/v0/precommit/2\"}) by (sector_from_worker_hostname)",
     "legendFormat": "{{ sector_from_worker_hostname }}"
    }
   ]
  },
  {
   "title": "seal/v0/commit/2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(lotus_miner_sealing_job{miner_id=\"$miner_id\", sector_task=\"seal/v0/commit/2\"}) by (sector_from_worker_hostname)",
     "legendFormat": "{{ sector_from_worker_hostname }}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(lotus_miner_net_peers{miner_id=\"$miner_id\"})"
    }
   ]
  },
  {
   "title": "Total In",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "lotus_miner_net_bandwidth{stats=\"TotalIn\",miner_id=\"$miner_id\"}"
    }
   ]
  },
  {
   "title": "Total Out",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "lotus_miner_net_bandwidth{stats=\"TotalOut\",miner_id=\"$miner_id\"}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 52 },
   "targets": [
    {
     "expr": "lotus_miner_net_peers{miner_id=\"$miner_id\"}"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "lotus_miner_net_bandwidth{stats=\"RateOut\",miner_id=\"$miner_id\"}",
     "legendFormat": "In"
    },
    {
     "expr": "lotus_miner_net_bandwidth{stats=\"RateIn\",miner_id=\"$miner_id\"}",
     "legendFormat": "Out"
    }
   ]
  },
  { "title": "Actor Control", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "lotus_actor_control_list{miner_id=\"$miner_id\"}"
    }
   ]
  }
 ]
}